@startuml
'https://plantuml.com/class-diagram

'Component <|-left-  ConcreteComponent
'Component <|-right- Decorator
'Decorator <|-down ConcreteDecoratorA
'Decorator <|-down ConcreteDecoratorB

interface Component{
{abstract}operation()
}

class ConcreteComponent implements Component{
  operation()
}

abstract class Decorator  implements Component {
  operation()
}

 Decorator   *--left--> Component

class ConcreteDecoratorA extends Decorator{
  operation()
}
class ConcreteDecoratorB  extends Decorator{
  operation()
}


@enduml